### ISSUE TITLE
Include `onlyargs`

### ISSUE THREAD

**Issue by vi** [rosetta-rs/argparse-rosetta-rs#74]
https://crates.io/crates/onlyargs

[Article](https://blog.kodewerx.org/2023/04/improving-build-times-for-derive-macros.html) about `onlyargs` mention `argparse-rosetta-rs`, but does not try to add the new parser to the comparison table for some reason.

**Comment by epage** [comment]
See https://www.reddit.com/r/rust/comments/12kaiw8/improving_build_times_for_derive_macros_by_3x_or/jg3ms63/
